[package]
name = "shwoop"
description = "Tool to serve static webpage with build-and-hot-reload feature"
repository = "https://github.com/Pistonite/shwoop"
authors = ["Pistonight <pistonknight@outlook.com>"]
version = "0.2.0"
edition = "2024"
license = "MIT"
keywords = ["hot-reload", "dev-server", "static-files", "web", "build"]
categories = ["development-tools", "web-programming::http-server", "command-line-utilities"]
include = [
    "dist/**/*.js",
    "dist/**/*.rs",
    "dist/**/*.js.map",
    "src/**/*.rs",
    "src/**/*.html",
    "/LICENSE",
]


[dependencies.cu]
package = "pistonite-cu"
version = "0.8.0"
features = [ "cli", "derive", "coroutine", "process" ]

[dependencies]
actix = "0.13.5"
actix-files = "0.6.10"
actix-web = "4.13.0"
actix-ws = "0.4.0"
dashmap = "6.1.0"
log = "0.4.29"
lol_html = "2.7.2"
tokio = "1"
oneshot = { version = "0.2.1", features = [ "async" ] }
watchexec = "8.2.0"
watchexec-events = "6.1.0"
watchexec-signals = "5.0.1"

[package.metadata.binstall.signing]
algorithm = "minisign"
pubkey = "RWThJQKJaXayoZBe0YV5LV4KFkQwcqQ6Fg9dJBz18JnpHGdf/cHUyKs+"
