version: '3'

includes:
  git:
    taskfile: ./node_modules/mono-dev/task/git.yaml
    internal: true
    optional: true
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true
  cargo:
    taskfile: ./node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  install:
    - pnpm install

  build:
    - task: ecma:app-build
    - cargo build {{.CLI_ARGS}}

  build-client:
    - task: ecma:app-build

  run:
    - task: ecma:app-build
    - cargo run -- {{.CLI_ARGS}}
    
  check:
    - task: ecma:check
    - task: cargo:clippy-all
    - task: cargo:fmt-check

  test:
    - cargo test

  fix:
    - task: ecma:fix
    - task: cargo:fmt-fix

  upgrade:
    - pnpm up mono-dev @types/node
    - pnpm dedupe
    - pnpm dedupe --check

  publish:
    cmds:
      - task: pre-publish
      - task: do-publish

  pre-publish:
    internal: true
    cmds:
      - task: git:check-modification
        vars:
          CHECK_MESSAGE: clean work tree is required before publishing
      - task: install
      - task: check
      - task: build
      - task: test
      - task: git:check-modification
        vars:
          CHECK_MESSAGE: modification found after preparing to publish!
  do-publish:
    internal: true
    vars:
      VERSION:
        sh: cargo run -- --version | tr -d 'shwoop '
    cmds:
      - git tag 'v{{.VERSION}}'
      - git push origin 'v{{.VERSION}}'
      - cargo publish --allow-dirty # the dist files are considered dirty
      
    

